#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspectacular
Version  : 0.70.7
Release  : 7
URL      : https://rubygems.org/downloads/rspectacular-0.70.7.gem
Source0  : https://rubygems.org/downloads/rspectacular-0.70.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rspectacular-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
Rspectacular
==============================================================================

%package bin
Summary: bin components for the rubygem-rspectacular package.
Group: Binaries

%description bin
bin components for the rubygem-rspectacular package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspectacular-0.70.7
gem spec %{SOURCE0} -l --ruby > rubygem-rspectacular.gemspec

%build
export LANG=C
gem build rubygem-rspectacular.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspectacular-0.70.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rspectacular-0.70.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/bin/deploy
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/bin/rspectacular_test_bootstrap
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/helpers/factories.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/helpers/null_objects.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/helpers/session_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/mock_authentications/omniauth.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/mock_authentications/omniauth/ebay.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/mock_authentications/omniauth/facebook.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/mock_authentications/omniauth/twitter.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/authentication.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/bullet.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/carrier_wave.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/code_climate.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/database_cleaner.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/devise.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/elasticsearch.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/email.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/factory_girl.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/fakeredis.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/mocks.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/omniauth.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/rails/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/rails/strong_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/recaptcha.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/referehencible.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/shoulda.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/sidekiq.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/simple_cov.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/singleton.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/stripe.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/test_after_commit.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/timecop.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/vcr.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/plugins/wisper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/spec_helpers/active_record_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/spec_helpers/active_record_connection_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/spec_helpers/rails_engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/expectations.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/failures.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/focused.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/formatters.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/garbage_collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/heroku.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/i18n.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/mocks.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/pending.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/random.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/support/selenium.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/vcr_matchers/uri_without_trailing_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspectacular-0.70.7/lib/rspectacular/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rspectacular-0.70.7.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/deploy
/usr/bin/rspectacular_test_bootstrap
