#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspectacular
Version  : 0.63.0
Release  : 3
URL      : https://rubygems.org/downloads/rspectacular-0.63.0.gem
Source0  : https://rubygems.org/downloads/rspectacular-0.63.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rspectacular-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
Rspectacular
==============================================================================

%package bin
Summary: bin components for the rubygem-rspectacular package.
Group: Binaries

%description bin
bin components for the rubygem-rspectacular package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspectacular-0.63.0
gem spec %{SOURCE0} -l --ruby > rubygem-rspectacular.gemspec

%build
gem build rubygem-rspectacular.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspectacular-0.63.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rspectacular-0.63.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ActionController/Parameters/cdesc-Parameters.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ActionController/cdesc-ActionController.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ActionMailer/cdesc-ActionMailer.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Capybara/Features/cdesc-Features.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Capybara/Features/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Capybara/cdesc-Capybara.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/CodeClimate/cdesc-CodeClimate.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/DatabaseCleaner/cdesc-DatabaseCleaner.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Elasticsearch/Extensions/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Elasticsearch/Extensions/cdesc-Extensions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Elasticsearch/cdesc-Elasticsearch.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Object/authenticate_api_as-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Object/factory_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Object/feature-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Object/null_described_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Ebay/authentication-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Ebay/cdesc-Ebay.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Facebook/authentication-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Facebook/cdesc-Facebook.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Twitter/authentication-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/Twitter/cdesc-Twitter.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/MockAuthentications/cdesc-MockAuthentications.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/OmniAuth/cdesc-OmniAuth.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/RSpec/Rails/RoutingExampleGroup/cdesc-RoutingExampleGroup.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/RSpec/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/cdesc-DeferredGarbageCollection.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/cycle_garbage_collector-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/enabled%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/garbage_last_collected_at-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/over_deferrment_threshold%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/reconsider-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/start-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/DeferredGarbageCollection/time_since_garbage_last_collected-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/NamespacedEngineControllerRouteFix/cdesc-NamespacedEngineControllerRouteFix.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/NamespacedEngineControllerRouteFix/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/VcrMatchers/UriWithoutTrailingId/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/VcrMatchers/UriWithoutTrailingId/cdesc-UriWithoutTrailingId.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/VcrMatchers/UriWithoutTrailingId/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/VcrMatchers/UriWithoutTrailingId/trailing_id_matcher-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/VcrMatchers/cdesc-VcrMatchers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Rspectacular/cdesc-Rspectacular.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ShouldaRoutingMatchers/cdesc-ShouldaRoutingMatchers.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/ShouldaRoutingMatchers/route-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Sidekiq/cdesc-Sidekiq.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/Stripe/cdesc-Stripe.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rspectacular-0.63.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/bin/deploy
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/bin/rspectacular_test_bootstrap
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/helpers/factories.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/helpers/null_objects.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/helpers/session_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/mock_authentications/omniauth.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/mock_authentications/omniauth/ebay.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/mock_authentications/omniauth/facebook.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/mock_authentications/omniauth/twitter.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/authentication.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/bullet.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/carrier_wave.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/code_climate.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/database_cleaner.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/devise.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/elasticsearch.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/email.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/factory_girl.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/fakeredis.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/features.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/omniauth.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/rails/engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/rails/strong_parameters.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/recaptcha.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/referehencible.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/shoulda.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/sidekiq.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/simple_cov.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/singleton.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/stripe.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/test_after_commit.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/timecop.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/vcr.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/webmock.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/plugins/wisper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/spec_helpers/active_record_basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/spec_helpers/active_record_connection_setup.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/spec_helpers/rails_engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/expectations.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/focused.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/formatters.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/garbage_collection.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/mocks.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/output.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/pending.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/random.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/support/selenium.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/vcr_matchers/uri_without_trailing_id.rb
/usr/lib64/ruby/gems/2.2.0/gems/rspectacular-0.63.0/lib/rspectacular/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rspectacular-0.63.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/deploy
/usr/bin/rspectacular_test_bootstrap
